services:
  - type: web
    name: motors74
    env: node
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    healthCheckPath: /api/healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://timeevdanil3:6wQvUwm2AxOdUoSA@motors74.zolkjbk.mongodb.net/?retryWrites=true&w=majority&appName=motors74
      - key: NEXTAUTH_URL
        value: https://motors74.onrender.com
      - key: NEXTAUTH_SECRET
        value: jVP4SJyVQqA0NBBqRbbayA6o7QQ6o1/h3bZN2xvQwQc=
      - key: NEXT_PUBLIC_API_URL
        value: https://motors74.onrender.com 