services:
  - type: web
    name: motors74
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: motors74-db
          property: connectionString
      - key: NEXTAUTH_URL
        value: https://motors74.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true 